function windData = createWindData(timeX, estimate, filtered, crosswind, crosswindFull, optimal, real)
    windData = struct();
    windData.time = timeX;
    windData.estimates = struct( ...
        'est', estimate, ...
        'estFilt', filtered, ...
        'estCWF', crosswind, ...
        'CWF', crosswindFull, ...
        'OPT', optimal, ...
        'real', real ...
    );
    
    % Add plotting properties for each estimate type
    windData.plotProps = struct();
    windData.plotProps.est = struct('Color', [0.565 0.808 0.98 0.2], 'LineWidth', 1);
    windData.plotProps.estFilt = struct('Color', [0 0.4470 0.7410], 'LineWidth', 2);
    windData.plotProps.estCWF = struct('Color', [0.9290 0.6940 0.1250], 'LineWidth', 2);
    windData.plotProps.CWF = struct('Color', [0.4660 0.6740 0.1880], 'LineWidth', 2);
    windData.plotProps.OPT = struct('Color', [0.4940 0.1840 0.5560], 'LineWidth', 2);
    windData.plotProps.real = struct('Color', [0.8500 0.3250 0.0980], 'LineWidth', 2, 'LineStyle', '--');
end